export interface Resource {
  title: string;
  slug: string;
  excerpt: string;
  category: 'Getting Started' | 'Legal' | 'Financial' | 'Growth';
  readTime: string;
  content: string;
}

export const RESOURCES: Resource[] = [
  {
    title: 'How to Define Your Nonprofit Mission Statement',
    slug: 'define-nonprofit-mission-statement',
    excerpt:
      'A compelling mission statement is the foundation of every successful nonprofit. Learn how to craft one that inspires donors, volunteers, and the community you serve.',
    category: 'Getting Started',
    readTime: '8 min read',
    content: `Your mission statement is the single most important sentence your nonprofit will ever write. It tells the world who you are, what you do, and why it matters.\n\nWhy Your Mission Statement Matters\n\nEvery decision your nonprofit makes should flow from your mission. It guides your programs, shapes your fundraising appeals, and determines your strategic direction. A strong mission statement also helps the IRS understand your charitable purpose when you apply for 501(c)(3) status.\n\nElements of an Effective Mission Statement\n\nThe best mission statements are clear, concise, and action-oriented. They answer three questions: Who do you serve? What do you do for them? What change do you seek to create? Aim for one to two sentences that anyone can understand.\n\nCommon Mistakes to Avoid\n\nAvoid jargon, vague language, or trying to cover too many goals. Your mission statement should be specific enough to differentiate you from other organizations but broad enough to allow growth. Do not confuse your mission with your vision: your mission describes what you do now, while your vision describes the future you want to create.\n\nStep-by-Step Process\n\nStart by listing the problems you want to solve. Then identify your target beneficiaries. Next, describe the primary activities or services you will provide. Finally, articulate the impact or change you hope to achieve. Combine these elements into a draft and refine it until every word earns its place.\n\nTesting Your Mission Statement\n\nShare your draft with people outside your organization. If they can explain what your nonprofit does after reading it once, you have succeeded. If they look confused, keep revising. A good mission statement should be memorable enough for your board members to recite from memory.`,
  },
  {
    title: 'Choosing the Right State to Incorporate Your Nonprofit',
    slug: 'choosing-state-to-incorporate',
    excerpt:
      'Filing fees, processing times, and regulations vary widely by state. This guide helps you pick the best state for incorporating your nonprofit organization.',
    category: 'Legal',
    readTime: '10 min read',
    content: `Choosing where to incorporate your nonprofit is one of the first legal decisions you will make, and it has lasting implications for fees, compliance, and operations.\n\nIncorporate Where You Operate\n\nIn most cases, the simplest choice is to incorporate in the state where your nonprofit will conduct most of its activities. This avoids the complexity and cost of registering as a foreign corporation in additional states.\n\nComparing Filing Fees\n\nFiling fees for nonprofit incorporation range from as low as 25 dollars in Texas to over 250 dollars in some northeastern states. While fees should not be the only factor, they can add up when you factor in annual report fees and registered agent costs.\n\nProcessing Times\n\nSome states process incorporation documents in as little as three business days, while others may take several weeks. If speed matters, check whether your state offers expedited processing for an additional fee.\n\nState-Specific Requirements\n\nSome states have unique requirements that affect nonprofits. For example, California requires nonprofits to register with the Attorney General before soliciting donations. New York requires court approval of your certificate of incorporation. Research your state's specific rules before filing.\n\nRegistered Agent Requirements\n\nEvery state requires a registered agent with a physical address in the state of incorporation. This can be an individual board member or a commercial registered agent service. Factor this cost into your decision.\n\nAnnual Compliance Obligations\n\nBeyond the initial filing, consider the ongoing compliance burden. Some states require annual reports, others require biennial reports, and a few have no reporting requirement at all. Understanding these obligations upfront prevents surprises later.`,
  },
  {
    title: 'Understanding 501(c)(3) Tax-Exempt Status',
    slug: 'understanding-501c3-tax-exempt-status',
    excerpt:
      'Everything you need to know about 501(c)(3) status: what it means, who qualifies, how to apply, and what obligations come with tax-exempt recognition.',
    category: 'Legal',
    readTime: '12 min read',
    content: `Obtaining 501(c)(3) status from the IRS is the gold standard for nonprofit organizations. It unlocks tax-deductible donations, grant eligibility, and public trust.\n\nWhat Is 501(c)(3) Status?\n\nSection 501(c)(3) of the Internal Revenue Code grants federal tax exemption to organizations operated exclusively for charitable, religious, educational, scientific, or literary purposes. This means your nonprofit does not pay federal income tax on revenue related to its exempt purpose.\n\nBenefits of 501(c)(3) Status\n\nThe most significant benefit is that donations to your organization become tax-deductible for donors. This dramatically increases your fundraising potential. You also gain eligibility for government and foundation grants, reduced postal rates, and exemption from federal unemployment tax.\n\nEligibility Requirements\n\nTo qualify, your organization must be organized and operated exclusively for exempt purposes. No part of your net earnings may benefit any private individual. You cannot participate in political campaigns, and lobbying activities must be limited.\n\nThe Application Process\n\nMost small nonprofits with expected annual revenues under 50,000 dollars can use the simplified Form 1023-EZ. Larger organizations must file the full Form 1023. Both require a 275 dollar or 600 dollar filing fee respectively. Processing times range from two weeks for the 1023-EZ to three to six months for the full 1023.\n\nMaintaining Your Status\n\nOnce granted, your tax-exempt status requires ongoing compliance. You must file Form 990 annually, avoid prohibited activities, and maintain accurate records. Failure to file for three consecutive years results in automatic revocation.\n\nCommon Pitfalls\n\nMany organizations lose their status due to private benefit violations, excessive lobbying, or simply forgetting to file their annual returns. Set up a compliance calendar and consider working with a nonprofit attorney for your first year.`,
  },
  {
    title: 'Creating a Nonprofit Budget: A First-Year Guide',
    slug: 'creating-nonprofit-budget-first-year',
    excerpt:
      'Your first-year budget sets the financial foundation for your nonprofit. Learn how to forecast revenue, plan expenses, and present a budget that satisfies your board and funders.',
    category: 'Financial',
    readTime: '9 min read',
    content: `A well-crafted budget is essential for nonprofit governance, grant applications, and financial sustainability. Here is how to build one for your first year.\n\nWhy Budgeting Matters for Nonprofits\n\nUnlike for-profit businesses that measure success by profit, nonprofits measure success by mission impact. But mission impact requires financial resources, and a budget is your plan for acquiring and deploying those resources effectively.\n\nRevenue Forecasting\n\nBe conservative with your first-year revenue projections. Common revenue sources for new nonprofits include individual donations, fundraising events, grants, corporate sponsorships, and program fees. For each source, estimate a realistic range and use the lower end for planning purposes.\n\nExpense Categories\n\nOrganize expenses into program costs, administrative costs, and fundraising costs. Program costs directly support your mission. Administrative costs include rent, insurance, accounting, and technology. Fundraising costs cover donor communications, events, and grant writing. Funders typically want to see at least 65 to 75 percent of your budget going to programs.\n\nStartup Costs to Consider\n\nYour first year includes one-time startup costs: incorporation fees, IRS filing fees, website development, initial marketing materials, and potentially legal and accounting fees. Budget these separately so your ongoing annual budget looks more sustainable.\n\nCash Flow Planning\n\nRevenue does not arrive evenly throughout the year. Many nonprofits receive a disproportionate share of donations in December. Plan for months when expenses exceed revenue by building a cash reserve or securing a line of credit.\n\nPresenting Your Budget\n\nYour board should approve the budget before each fiscal year. Present it clearly with categories, line items, and brief justifications. Many funders also require a budget as part of grant applications, so having a polished document ready saves time.`,
  },
  {
    title: 'Fundraising Compliance: What Every Nonprofit Must Know',
    slug: 'fundraising-compliance-guide',
    excerpt:
      'Before you ask for your first dollar, understand the legal requirements for nonprofit fundraising, including state registration, donor receipts, and solicitation rules.',
    category: 'Financial',
    readTime: '11 min read',
    content: `Fundraising is the lifeblood of most nonprofits, but it comes with legal obligations that vary by state. Failing to comply can result in fines, penalties, and reputational damage.\n\nCharitable Solicitation Registration\n\nApproximately 40 states require nonprofits to register before soliciting donations from residents of that state. This applies to online fundraising as well, meaning a single website can trigger registration requirements in multiple states. Start with the states where you expect to receive the most donations.\n\nDonor Acknowledgment Requirements\n\nThe IRS requires written acknowledgment for any single donation of 250 dollars or more. The acknowledgment must include the amount, a statement that no goods or services were provided in exchange, and your organization's name. For donations over 75 dollars where something was given in return, you must provide a good-faith estimate of the value.\n\nOnline Fundraising Rules\n\nOnline fundraising platforms like GoFundMe and Facebook Fundraisers have their own compliance considerations. Make sure donations processed through third-party platforms are properly recorded and acknowledged. Also verify that the platform is registered as a professional fundraiser in states that require it.\n\nGrant Compliance\n\nGrants come with strings attached. Most grantors require detailed reporting on how funds were used. Some restrict funds to specific programs or time periods. Track grant expenditures separately and maintain thorough documentation.\n\nFundraising Best Practices\n\nAlways be transparent about how donations will be used. Never mislead donors about your tax-exempt status or the deductibility of their contributions. Maintain a donor privacy policy and honor opt-out requests promptly.\n\nPenalties for Non-Compliance\n\nPenalties for fundraising violations range from warning letters to significant fines. In extreme cases, states can revoke your authority to solicit donations entirely. The cost of compliance is always less than the cost of violations.`,
  },
  {
    title: 'Scaling Your Nonprofit: From Local to National Impact',
    slug: 'scaling-nonprofit-local-to-national',
    excerpt:
      'Ready to expand your reach? Learn proven strategies for growing your nonprofit from a local initiative to a nationally recognized organization.',
    category: 'Growth',
    readTime: '10 min read',
    content: `Growing a nonprofit beyond its initial community requires strategic planning, infrastructure investment, and a clear understanding of what got you here and what will get you there.\n\nWhen to Scale\n\nNot every nonprofit should scale. Before expanding, ask whether your model has been proven effective, whether demand exists in new markets, and whether your organization has the capacity to manage growth. Premature scaling is one of the top reasons nonprofits fail.\n\nBuilding Scalable Systems\n\nInvest in technology and processes that can handle increased volume without proportionally increasing costs. This includes donor management software, financial systems, and program delivery platforms. Manual processes that work for a small organization will break as you grow.\n\nExpanding Your Board\n\nAs you scale, your board needs to evolve. Look for members with expertise in areas like national fundraising, legal compliance across multiple states, strategic planning, and financial oversight. A diverse board with relevant experience is your most valuable growth asset.\n\nFunding Your Growth\n\nScaling requires capital. Develop a diversified funding strategy that includes individual donors, institutional grants, corporate partnerships, and earned revenue. Many foundations specifically fund organizational capacity building, which can support your scaling efforts.\n\nMulti-State Compliance\n\nOperating in multiple states means complying with each state's nonprofit regulations, charitable solicitation laws, and employment rules. Create a compliance checklist for each state and consider hiring a compliance specialist or using a multi-state registration service.\n\nMeasuring Impact at Scale\n\nAs you grow, your impact measurement becomes both more important and more complex. Develop standardized metrics that can be tracked across locations and programs. Invest in data collection tools and reporting systems that provide real-time visibility into your outcomes.\n\nStrategic Partnerships\n\nPartnering with established organizations can accelerate your growth while reducing risk. Look for partners whose missions complement yours and who have infrastructure in your target markets. Fiscal sponsorship arrangements can also help you test new markets before committing to full expansion.`,
  },
];
