// ---------------------------------------------------------------------------
// TurboCharity – Comprehensive US state data for nonprofit incorporation
// ---------------------------------------------------------------------------

export interface StateInfo {
  name: string;
  slug: string;
  abbreviation: string;
  filingFee: number;
  processingTime: string;
  requiresPublicationNotice: boolean;
  onlineFilingAvailable: boolean;
  secretaryOfStateUrl: string;
}

// ---------------------------------------------------------------------------
// 15 states with individually researched, accurate data
// ---------------------------------------------------------------------------

const RESEARCHED_STATES: StateInfo[] = [
  {
    name: 'California',
    slug: 'california',
    abbreviation: 'CA',
    filingFee: 30,
    processingTime: '3-5 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.ca.gov/business-programs/business-entities',
  },
  {
    name: 'New York',
    slug: 'new-york',
    abbreviation: 'NY',
    filingFee: 75,
    processingTime: '7-14 business days',
    requiresPublicationNotice: true,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://dos.ny.gov/corporations-and-businesses',
  },
  {
    name: 'Texas',
    slug: 'texas',
    abbreviation: 'TX',
    filingFee: 25,
    processingTime: '3-5 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.state.tx.us/corp/index.shtml',
  },
  {
    name: 'Florida',
    slug: 'florida',
    abbreviation: 'FL',
    filingFee: 70,
    processingTime: '3-5 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://dos.fl.gov/sunbiz/',
  },
  {
    name: 'Illinois',
    slug: 'illinois',
    abbreviation: 'IL',
    filingFee: 50,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.ilsos.gov/departments/business_services/',
  },
  {
    name: 'Pennsylvania',
    slug: 'pennsylvania',
    abbreviation: 'PA',
    filingFee: 125,
    processingTime: '7-10 business days',
    requiresPublicationNotice: true,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.dos.pa.gov/BusinessCharities/Business/Pages/default.aspx',
  },
  {
    name: 'Ohio',
    slug: 'ohio',
    abbreviation: 'OH',
    filingFee: 99,
    processingTime: '3-5 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.ohiosos.gov/businesses/',
  },
  {
    name: 'Georgia',
    slug: 'georgia',
    abbreviation: 'GA',
    filingFee: 100,
    processingTime: '7-10 business days',
    requiresPublicationNotice: true,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sos.ga.gov/corporations-division',
  },
  {
    name: 'North Carolina',
    slug: 'north-carolina',
    abbreviation: 'NC',
    filingFee: 60,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sosnc.gov/divisions/business_registration',
  },
  {
    name: 'Michigan',
    slug: 'michigan',
    abbreviation: 'MI',
    filingFee: 20,
    processingTime: '5-7 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.michigan.gov/lara/bureau-list/bcs',
  },
  {
    name: 'New Jersey',
    slug: 'new-jersey',
    abbreviation: 'NJ',
    filingFee: 75,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.njportal.com/DOR/BusinessFormation',
  },
  {
    name: 'Virginia',
    slug: 'virginia',
    abbreviation: 'VA',
    filingFee: 75,
    processingTime: '3-5 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.scc.virginia.gov/pages/Business-Entity-Search',
  },
  {
    name: 'Washington',
    slug: 'washington',
    abbreviation: 'WA',
    filingFee: 30,
    processingTime: '5-7 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.wa.gov/corporations-charities',
  },
  {
    name: 'Massachusetts',
    slug: 'massachusetts',
    abbreviation: 'MA',
    filingFee: 35,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sec.state.ma.us/cor/coridx.htm',
  },
  {
    name: 'Arizona',
    slug: 'arizona',
    abbreviation: 'AZ',
    filingFee: 40,
    processingTime: '5-10 business days',
    requiresPublicationNotice: true,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://azsos.gov/business',
  },
];

// ---------------------------------------------------------------------------
// Remaining states + DC with reasonable default data
// ---------------------------------------------------------------------------

const REMAINING_STATES: StateInfo[] = [
  {
    name: 'Alabama',
    slug: 'alabama',
    abbreviation: 'AL',
    filingFee: 200,
    processingTime: '5-7 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.alabama.gov/business-entities',
  },
  {
    name: 'Alaska',
    slug: 'alaska',
    abbreviation: 'AK',
    filingFee: 250,
    processingTime: '10-15 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.commerce.alaska.gov/web/cbpl/corporations',
  },
  {
    name: 'Arkansas',
    slug: 'arkansas',
    abbreviation: 'AR',
    filingFee: 45,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.arkansas.gov/business-commercial-services-bcs',
  },
  {
    name: 'Colorado',
    slug: 'colorado',
    abbreviation: 'CO',
    filingFee: 50,
    processingTime: '5-7 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.state.co.us/pubs/business/main.html',
  },
  {
    name: 'Connecticut',
    slug: 'connecticut',
    abbreviation: 'CT',
    filingFee: 50,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://portal.ct.gov/SOTS/Business-Services',
  },
  {
    name: 'Delaware',
    slug: 'delaware',
    abbreviation: 'DE',
    filingFee: 89,
    processingTime: '3-5 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://corp.delaware.gov/',
  },
  {
    name: 'Hawaii',
    slug: 'hawaii',
    abbreviation: 'HI',
    filingFee: 25,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://cca.hawaii.gov/breg/',
  },
  {
    name: 'Idaho',
    slug: 'idaho',
    abbreviation: 'ID',
    filingFee: 30,
    processingTime: '5-7 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sos.idaho.gov/business/',
  },
  {
    name: 'Indiana',
    slug: 'indiana',
    abbreviation: 'IN',
    filingFee: 30,
    processingTime: '5-7 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.in.gov/sos/business/index.htm',
  },
  {
    name: 'Iowa',
    slug: 'iowa',
    abbreviation: 'IA',
    filingFee: 20,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sos.iowa.gov/business/index.html',
  },
  {
    name: 'Kansas',
    slug: 'kansas',
    abbreviation: 'KS',
    filingFee: 20,
    processingTime: '3-5 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.ks.gov/business/business.html',
  },
  {
    name: 'Kentucky',
    slug: 'kentucky',
    abbreviation: 'KY',
    filingFee: 8,
    processingTime: '3-5 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.ky.gov/bus/Pages/default.aspx',
  },
  {
    name: 'Louisiana',
    slug: 'louisiana',
    abbreviation: 'LA',
    filingFee: 75,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.la.gov/BusinessServices/Pages/default.aspx',
  },
  {
    name: 'Maine',
    slug: 'maine',
    abbreviation: 'ME',
    filingFee: 40,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.maine.gov/sos/cec/corp/',
  },
  {
    name: 'Maryland',
    slug: 'maryland',
    abbreviation: 'MD',
    filingFee: 170,
    processingTime: '7-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://dat.maryland.gov/businesses',
  },
  {
    name: 'Minnesota',
    slug: 'minnesota',
    abbreviation: 'MN',
    filingFee: 70,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.state.mn.us/business-liens/',
  },
  {
    name: 'Mississippi',
    slug: 'mississippi',
    abbreviation: 'MS',
    filingFee: 50,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.ms.gov/business-services',
  },
  {
    name: 'Missouri',
    slug: 'missouri',
    abbreviation: 'MO',
    filingFee: 25,
    processingTime: '5-7 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.mo.gov/business',
  },
  {
    name: 'Montana',
    slug: 'montana',
    abbreviation: 'MT',
    filingFee: 20,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sosmt.gov/business/',
  },
  {
    name: 'Nebraska',
    slug: 'nebraska',
    abbreviation: 'NE',
    filingFee: 10,
    processingTime: '3-5 business days',
    requiresPublicationNotice: true,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sos.nebraska.gov/business-services',
  },
  {
    name: 'Nevada',
    slug: 'nevada',
    abbreviation: 'NV',
    filingFee: 50,
    processingTime: '3-5 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.nvsos.gov/sos/businesses',
  },
  {
    name: 'New Hampshire',
    slug: 'new-hampshire',
    abbreviation: 'NH',
    filingFee: 25,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.nh.gov/corporation-division',
  },
  {
    name: 'New Mexico',
    slug: 'new-mexico',
    abbreviation: 'NM',
    filingFee: 25,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.nm.gov/business-services/',
  },
  {
    name: 'North Dakota',
    slug: 'north-dakota',
    abbreviation: 'ND',
    filingFee: 40,
    processingTime: '5-7 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sos.nd.gov/business/business-services',
  },
  {
    name: 'Oklahoma',
    slug: 'oklahoma',
    abbreviation: 'OK',
    filingFee: 25,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.ok.gov/business/default.aspx',
  },
  {
    name: 'Oregon',
    slug: 'oregon',
    abbreviation: 'OR',
    filingFee: 50,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sos.oregon.gov/business/Pages/default.aspx',
  },
  {
    name: 'Rhode Island',
    slug: 'rhode-island',
    abbreviation: 'RI',
    filingFee: 35,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.ri.gov/divisions/business-services',
  },
  {
    name: 'South Carolina',
    slug: 'south-carolina',
    abbreviation: 'SC',
    filingFee: 25,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.sos.sc.gov/online-filings',
  },
  {
    name: 'South Dakota',
    slug: 'south-dakota',
    abbreviation: 'SD',
    filingFee: 30,
    processingTime: '5-7 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sdsos.gov/business-services/default.aspx',
  },
  {
    name: 'Tennessee',
    slug: 'tennessee',
    abbreviation: 'TN',
    filingFee: 100,
    processingTime: '5-7 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sos.tn.gov/business-services',
  },
  {
    name: 'Utah',
    slug: 'utah',
    abbreviation: 'UT',
    filingFee: 30,
    processingTime: '3-5 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://corporations.utah.gov/',
  },
  {
    name: 'Vermont',
    slug: 'vermont',
    abbreviation: 'VT',
    filingFee: 125,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sos.vermont.gov/corporations/',
  },
  {
    name: 'West Virginia',
    slug: 'west-virginia',
    abbreviation: 'WV',
    filingFee: 15,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sos.wv.gov/business-licensing/Pages/default.aspx',
  },
  {
    name: 'Wisconsin',
    slug: 'wisconsin',
    abbreviation: 'WI',
    filingFee: 35,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://www.wdfi.org/corporations/',
  },
  {
    name: 'Wyoming',
    slug: 'wyoming',
    abbreviation: 'WY',
    filingFee: 25,
    processingTime: '5-15 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://sos.wyo.gov/business/default.aspx',
  },
  {
    name: 'District of Columbia',
    slug: 'district-of-columbia',
    abbreviation: 'DC',
    filingFee: 80,
    processingTime: '5-10 business days',
    requiresPublicationNotice: false,
    onlineFilingAvailable: true,
    secretaryOfStateUrl: 'https://dcra.dc.gov/service/corporate-registration',
  },
];

// ---------------------------------------------------------------------------
// Combined & sorted alphabetically
// ---------------------------------------------------------------------------

export const STATES: StateInfo[] = [...RESEARCHED_STATES, ...REMAINING_STATES].sort((a, b) =>
  a.name.localeCompare(b.name),
);

// ---------------------------------------------------------------------------
// Helper utilities
// ---------------------------------------------------------------------------

/** Look up a state by its URL slug. */
export function getStateBySlug(slug: string): StateInfo | undefined {
  return STATES.find((s) => s.slug === slug);
}

/** Look up a state by its two-letter abbreviation. */
export function getStateByAbbreviation(abbreviation: string): StateInfo | undefined {
  return STATES.find((s) => s.abbreviation === abbreviation.toUpperCase());
}
