import type { Metadata } from 'next';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Container from '@/components/Container';
import StructuredData from '@/components/StructuredData';
import { getFAQSchema } from '@/lib/structured-data';

export const metadata: Metadata = {
  title: 'Pricing - Start Your Nonprofit for Free | TurboCharity',
  description:
    'Transparent pricing for nonprofit formation. Start free, or get AI-powered document generation and guided IRS filing from $49. Compare with traditional lawyer costs.',
  openGraph: {
    title: 'Pricing - Start Your Nonprofit for Free | TurboCharity',
    description:
      'Transparent pricing for nonprofit formation. Start free, or get AI-powered document generation from $49.',
  },
};

const tiers = [
  {
    name: 'Free',
    price: '$0',
    period: '',
    description: 'Essential tools and guides to start exploring nonprofit creation on your own.',
    cta: 'Start Free',
    ctaStyle: 'border-2 border-primary text-primary hover:bg-primary/5',
    highlighted: false,
    features: [
      'Nonprofit readiness assessment',
      'Step-by-step formation checklist',
      'Mission statement builder',
      'State requirements lookup (all 50 states)',
      'Blog articles & educational resources',
      'Community forum access',
    ],
    excludedFeatures: [
      'AI document generation',
      'IRS Form 1023-EZ auto-fill',
      'Bylaws generator',
      'Priority support',
      'Compliance calendar',
      'Board resolution templates',
    ],
  },
  {
    name: 'Starter',
    price: '$49',
    period: 'one-time',
    description: 'Everything you need to incorporate and file for 501(c)(3) status with confidence.',
    cta: 'Get Started',
    ctaStyle: 'bg-primary text-white hover:bg-blue-700',
    highlighted: true,
    features: [
      'Everything in Free, plus:',
      'AI-generated Articles of Incorporation',
      'AI-generated Bylaws (customized)',
      'Conflict of Interest Policy',
      'IRS Form 1023-EZ auto-fill & review',
      'EIN application guide',
      'State filing instructions packet',
      'Email support (48hr response)',
    ],
    excludedFeatures: [
      'Expedited document review',
      'Compliance calendar & reminders',
      'Board resolution templates',
      'Annual filing support',
    ],
  },
  {
    name: 'Pro',
    price: '$149',
    period: 'one-time',
    description: 'Complete formation suite with ongoing compliance support and priority assistance.',
    cta: 'Go Pro',
    ctaStyle: 'bg-dark text-white hover:bg-gray-800',
    highlighted: false,
    features: [
      'Everything in Starter, plus:',
      'Expedited document review (24hr)',
      'Priority email & chat support',
      'Compliance calendar & reminders',
      'Board resolution templates (12+)',
      'Donor acknowledgment letter templates',
      'Annual Form 990-N filing guide',
      'State charitable registration guide',
      'Fundraising policy template',
      '1 year of compliance monitoring',
    ],
    excludedFeatures: [],
  },
];

const comparisonFeatures = [
  { feature: 'Articles of Incorporation', free: false, starter: true, pro: true, lawyer: true },
  { feature: 'Custom Bylaws', free: false, starter: true, pro: true, lawyer: true },
  { feature: 'Conflict of Interest Policy', free: false, starter: true, pro: true, lawyer: true },
  { feature: 'IRS Form 1023-EZ Preparation', free: false, starter: true, pro: true, lawyer: true },
  { feature: 'EIN Application Guidance', free: false, starter: true, pro: true, lawyer: true },
  { feature: 'State Filing Instructions', free: false, starter: true, pro: true, lawyer: true },
  { feature: 'Compliance Calendar', free: false, starter: false, pro: true, lawyer: false },
  { feature: 'Board Resolution Templates', free: false, starter: false, pro: true, lawyer: '$200+/ea' },
  { feature: 'Ongoing Compliance Support', free: false, starter: false, pro: true, lawyer: '$150+/hr' },
  { feature: 'Donor Letter Templates', free: false, starter: false, pro: true, lawyer: '$100+' },
  { feature: 'Annual Filing Support', free: false, starter: false, pro: true, lawyer: '$500+/yr' },
  { feature: 'Processing Time', free: 'Self-paced', starter: '3-5 days', pro: '1-3 days', lawyer: '4-12 weeks' },
  { feature: 'Total Typical Cost', free: '$0', starter: '$49 + fees', pro: '$149 + fees', lawyer: '$2,000-$5,000+' },
];

const pricingFaqs = [
  {
    question: 'Are there additional fees beyond the TurboCharity price?',
    answer:
      'Yes — TurboCharity\'s pricing covers our platform and document generation services. You\'ll also need to pay government filing fees, which include your state\'s incorporation fee ($8-$300 depending on the state) and the IRS Form 1023-EZ fee ($275). These fees go directly to the government and apply regardless of how you file.',
  },
  {
    question: 'How does TurboCharity compare to hiring a nonprofit lawyer?',
    answer:
      'A nonprofit attorney typically charges $1,500 to $5,000+ for the full formation process, and the timeline is usually 4 to 12 weeks. TurboCharity provides the same essential documents (Articles of Incorporation, bylaws, conflict of interest policy, and IRS application preparation) for $49 to $149 and completes the process in 1 to 5 days. Our AI generates documents based on the same legal requirements attorneys follow, customized to your state and organization.',
  },
  {
    question: 'What is your refund policy?',
    answer:
      'We offer a 30-day money-back guarantee on all paid plans. If you\'re not satisfied with TurboCharity for any reason, contact our support team within 30 days of purchase and we\'ll issue a full refund — no questions asked. Government filing fees paid directly to the IRS or your state are non-refundable.',
  },
  {
    question: 'Can I start with Free and upgrade later?',
    answer:
      'Absolutely! Many founders start with our Free tier to explore the platform and learn about the formation process, then upgrade to Starter or Pro when they\'re ready to generate documents and file. Any progress you make on the Free tier carries over when you upgrade.',
  },
  {
    question: 'Do I need the Pro plan?',
    answer:
      'The Starter plan covers everything you need to form your nonprofit and apply for 501(c)(3) status. The Pro plan is ideal if you want ongoing compliance support, faster processing, priority support, and templates for post-formation activities like board meetings and donor management. If you\'re a first-time founder, Pro gives you peace of mind with a full year of compliance monitoring.',
  },
  {
    question: 'Is the price really one-time? No subscriptions?',
    answer:
      'Yes, both Starter ($49) and Pro ($149) are one-time payments, not subscriptions. You get lifetime access to your generated documents and the resources included in your plan. The Pro plan includes 1 year of compliance monitoring, which can be renewed annually at a discounted rate if desired.',
  },
];

function CheckIcon({ className = '' }: { className?: string }) {
  return (
    <svg className={`h-5 w-5 ${className}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
    </svg>
  );
}

function XIcon({ className = '' }: { className?: string }) {
  return (
    <svg className={`h-5 w-5 ${className}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
      <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
    </svg>
  );
}

export default function PricingPage() {
  return (
    <>
      <StructuredData data={getFAQSchema(pricingFaqs)} />
      <Header />
      <main className="min-h-screen">
        {/* Hero */}
        <section className="bg-gradient-to-b from-primary/5 to-white py-16 md:py-24">
          <Container className="text-center">
            <span className="mb-4 inline-block rounded-full bg-primary/10 px-4 py-1.5 text-sm font-semibold text-primary">
              Simple, Transparent Pricing
            </span>
            <h1 className="mx-auto max-w-3xl text-4xl font-extrabold leading-tight text-dark md:text-5xl">
              Start Your Nonprofit for{' '}
              <span className="text-primary">a Fraction of the Cost</span>
            </h1>
            <p className="mx-auto mt-6 max-w-2xl text-lg text-gray-600">
              Why spend $2,000-$5,000+ on a lawyer when TurboCharity can get you there for as
              little as $49? One-time payment. No subscriptions. 30-day money-back guarantee.
            </p>
          </Container>
        </section>

        {/* Pricing Tiers */}
        <section className="pb-16 md:pb-24">
          <Container>
            <div className="grid gap-8 md:grid-cols-3">
              {tiers.map((tier) => (
                <div
                  key={tier.name}
                  className={`relative flex flex-col rounded-2xl border p-8 ${
                    tier.highlighted
                      ? 'border-primary bg-white shadow-xl shadow-primary/10 ring-2 ring-primary'
                      : 'border-gray-200 bg-white shadow-sm'
                  }`}
                >
                  {tier.highlighted && (
                    <div className="absolute -top-4 left-1/2 -translate-x-1/2">
                      <span className="rounded-full bg-primary px-4 py-1 text-xs font-bold uppercase tracking-wider text-white">
                        Most Popular
                      </span>
                    </div>
                  )}

                  <div className="mb-6">
                    <h3 className="text-xl font-bold text-dark">{tier.name}</h3>
                    <div className="mt-3 flex items-baseline gap-1">
                      <span className="text-4xl font-extrabold text-dark">{tier.price}</span>
                      {tier.period && (
                        <span className="text-sm font-medium text-gray-500">/{tier.period}</span>
                      )}
                    </div>
                    <p className="mt-3 text-sm text-gray-600">{tier.description}</p>
                  </div>

                  <Link
                    href="#"
                    className={`mb-8 block rounded-lg px-6 py-3 text-center text-sm font-bold transition-colors ${tier.ctaStyle}`}
                  >
                    {tier.cta}
                  </Link>

                  <div className="flex-1">
                    <p className="mb-4 text-xs font-semibold uppercase tracking-wider text-gray-500">
                      What&apos;s included
                    </p>
                    <ul className="space-y-3">
                      {tier.features.map((feature) => (
                        <li key={feature} className="flex items-start gap-3 text-sm text-gray-700">
                          <CheckIcon className="mt-0.5 shrink-0 text-secondary" />
                          {feature}
                        </li>
                      ))}
                      {tier.excludedFeatures.map((feature) => (
                        <li key={feature} className="flex items-start gap-3 text-sm text-gray-400">
                          <XIcon className="mt-0.5 shrink-0 text-gray-300" />
                          {feature}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>

            {/* Money-back guarantee badge */}
            <div className="mt-12 flex items-center justify-center gap-4 rounded-xl border border-secondary/30 bg-secondary/5 px-8 py-5">
              <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-secondary/10">
                <svg
                  className="h-7 w-7 text-secondary"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth={1.5}
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z"
                  />
                </svg>
              </div>
              <div>
                <p className="font-bold text-dark">30-Day Money-Back Guarantee</p>
                <p className="text-sm text-gray-600">
                  Not satisfied? Get a full refund within 30 days. No questions asked. Government
                  filing fees are non-refundable.
                </p>
              </div>
            </div>
          </Container>
        </section>

        {/* Feature Comparison Table */}
        <section className="bg-gray-50 py-16 md:py-24">
          <Container>
            <div className="mb-12 text-center">
              <h2 className="text-3xl font-bold text-dark md:text-4xl">
                Detailed Feature Comparison
              </h2>
              <p className="mx-auto mt-4 max-w-2xl text-lg text-gray-600">
                See exactly what you get with each plan — and how TurboCharity compares to hiring a
                traditional nonprofit attorney.
              </p>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full min-w-[700px] rounded-xl border border-gray-200 bg-white text-left text-sm shadow-sm">
                <thead>
                  <tr className="border-b border-gray-200 bg-gray-50">
                    <th className="px-6 py-4 font-bold text-dark">Feature</th>
                    <th className="px-6 py-4 text-center font-bold text-dark">Free</th>
                    <th className="px-6 py-4 text-center font-bold text-primary">
                      Starter ($49)
                    </th>
                    <th className="px-6 py-4 text-center font-bold text-dark">Pro ($149)</th>
                    <th className="px-6 py-4 text-center font-bold text-gray-500">
                      Traditional Lawyer
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {comparisonFeatures.map((row, idx) => (
                    <tr
                      key={row.feature}
                      className={idx % 2 === 0 ? 'bg-white' : 'bg-gray-50/50'}
                    >
                      <td className="px-6 py-3.5 font-medium text-gray-900">{row.feature}</td>
                      {(['free', 'starter', 'pro', 'lawyer'] as const).map((plan) => {
                        const value = row[plan];
                        return (
                          <td key={plan} className="px-6 py-3.5 text-center">
                            {value === true ? (
                              <CheckIcon className="mx-auto text-secondary" />
                            ) : value === false ? (
                              <XIcon className="mx-auto text-gray-300" />
                            ) : (
                              <span className="text-sm font-medium text-gray-700">
                                {value}
                              </span>
                            )}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Container>
        </section>

        {/* Cost Comparison Callout */}
        <section className="py-16 md:py-24">
          <Container>
            <div className="mx-auto max-w-4xl rounded-2xl bg-dark p-10 md:p-14">
              <h2 className="mb-8 text-center text-3xl font-bold text-white">
                The True Cost of Starting a Nonprofit
              </h2>
              <div className="grid gap-8 md:grid-cols-2">
                <div className="rounded-xl bg-white/10 p-6">
                  <h3 className="mb-4 text-lg font-bold text-red-400">
                    Traditional Route (Lawyer)
                  </h3>
                  <ul className="space-y-3 text-sm text-gray-300">
                    <li className="flex justify-between">
                      <span>Attorney fees</span>
                      <span className="font-semibold text-white">$1,500 - $5,000</span>
                    </li>
                    <li className="flex justify-between">
                      <span>State incorporation fee</span>
                      <span className="font-semibold text-white">$8 - $300</span>
                    </li>
                    <li className="flex justify-between">
                      <span>IRS Form 1023-EZ fee</span>
                      <span className="font-semibold text-white">$275</span>
                    </li>
                    <li className="flex justify-between border-t border-white/20 pt-3">
                      <span className="font-bold text-white">Total</span>
                      <span className="font-bold text-red-400">$1,783 - $5,575+</span>
                    </li>
                    <li className="flex justify-between text-xs">
                      <span>Timeline</span>
                      <span>4-12 weeks</span>
                    </li>
                  </ul>
                </div>

                <div className="rounded-xl bg-primary/20 p-6 ring-2 ring-primary/40">
                  <h3 className="mb-4 text-lg font-bold text-secondary">
                    TurboCharity (Starter)
                  </h3>
                  <ul className="space-y-3 text-sm text-gray-300">
                    <li className="flex justify-between">
                      <span>TurboCharity Starter plan</span>
                      <span className="font-semibold text-white">$49</span>
                    </li>
                    <li className="flex justify-between">
                      <span>State incorporation fee</span>
                      <span className="font-semibold text-white">$8 - $300</span>
                    </li>
                    <li className="flex justify-between">
                      <span>IRS Form 1023-EZ fee</span>
                      <span className="font-semibold text-white">$275</span>
                    </li>
                    <li className="flex justify-between border-t border-white/20 pt-3">
                      <span className="font-bold text-white">Total</span>
                      <span className="font-bold text-secondary">$332 - $624</span>
                    </li>
                    <li className="flex justify-between text-xs">
                      <span>Timeline</span>
                      <span>3-5 days</span>
                    </li>
                  </ul>
                </div>
              </div>

              <p className="mt-8 text-center text-lg font-semibold text-white">
                Save up to <span className="text-secondary">$4,951</span> compared to traditional
                attorney costs
              </p>
            </div>
          </Container>
        </section>

        {/* FAQ */}
        <section className="bg-gray-50 py-16 md:py-24">
          <Container>
            <div className="mb-12 text-center">
              <h2 className="text-3xl font-bold text-dark md:text-4xl">
                Frequently Asked Questions
              </h2>
              <p className="mx-auto mt-4 max-w-2xl text-lg text-gray-600">
                Common questions about TurboCharity pricing, features, and how we compare.
              </p>
            </div>

            <div className="mx-auto max-w-3xl divide-y divide-gray-200">
              {pricingFaqs.map((faq) => (
                <details key={faq.question} className="group py-6">
                  <summary className="flex cursor-pointer items-center justify-between text-left text-lg font-semibold text-dark transition-colors hover:text-primary">
                    {faq.question}
                    <svg
                      className="ml-4 h-5 w-5 shrink-0 text-gray-400 transition-transform group-open:rotate-180"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth={2}
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                    </svg>
                  </summary>
                  <p className="mt-4 text-base leading-relaxed text-gray-600">{faq.answer}</p>
                </details>
              ))}
            </div>
          </Container>
        </section>

        {/* Bottom CTA */}
        <section className="bg-gradient-to-r from-primary to-blue-700 py-16 md:py-24">
          <Container className="text-center">
            <h2 className="text-3xl font-bold text-white md:text-4xl">
              Ready to Start Your Nonprofit?
            </h2>
            <p className="mx-auto mt-4 max-w-2xl text-lg text-blue-100">
              Join thousands of founders who have launched their nonprofits with TurboCharity.
              Start free, upgrade when you&apos;re ready.
            </p>
            <div className="mt-8 flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
              <Link
                href="#"
                className="inline-flex items-center gap-2 rounded-lg bg-white px-8 py-3.5 text-sm font-bold text-primary transition-colors hover:bg-gray-100"
              >
                Get Started Free
                <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                </svg>
              </Link>
              <Link
                href="/blog"
                className="inline-flex items-center gap-2 rounded-lg border-2 border-white/30 px-8 py-3.5 text-sm font-bold text-white transition-colors hover:bg-white/10"
              >
                Learn More
              </Link>
            </div>
          </Container>
        </section>
      </main>
      <Footer />
    </>
  );
}
