"use client";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Button from "@/components/Button";
import Container from "@/components/Container";
import NewsletterSignup from "@/components/NewsletterSignup";

/* ------------------------------------------------------------------ */
/*  Data                                                               */
/* ------------------------------------------------------------------ */

const stats = [
  { value: "10,000+", label: "Nonprofits Created" },
  { value: "$3,000+", label: "Saved in Legal Fees" },
  { value: "50", label: "State Coverage" },
];

const steps = [
  {
    number: "1",
    title: "Tell Us Your Mission",
    description:
      "Answer a few simple questions about your nonprofit\u2019s purpose, structure, and goals. Our guided wizard makes it easy \u2014 no legal jargon required.",
    icon: "\uD83D\uDCDD",
  },
  {
    number: "2",
    title: "We Generate Everything",
    description:
      "Our AI engine creates your bylaws, articles of incorporation, conflict-of-interest policies, and auto-fills IRS Form 1023-EZ \u2014 all customized to your state.",
    icon: "\u2699\uFE0F",
  },
  {
    number: "3",
    title: "File & Launch",
    description:
      "We handle state filing, EIN registration, and IRS submission so you can focus on your mission. Track every step from your dashboard.",
    icon: "\uD83D\uDE80",
  },
];

const features = [
  {
    icon: "\uD83C\uDFDB\uFE0F",
    title: "State-Specific Incorporation",
    description:
      "Automatically generates articles of incorporation tailored to your state\u2019s exact requirements and filing procedures.",
  },
  {
    icon: "\uD83D\uDCDC",
    title: "AI-Generated Bylaws",
    description:
      "Comprehensive bylaws drafted by AI, covering governance, meetings, officers, and amendment procedures for your organization.",
  },
  {
    icon: "\uD83D\uDCCB",
    title: "IRS Form 1023-EZ Auto-Fill",
    description:
      "Answers intelligently mapped to every field on the 1023-EZ so you can apply for tax-exempt status with confidence.",
  },
  {
    icon: "\uD83D\uDCCA",
    title: "Compliance Dashboard",
    description:
      "Stay on top of annual filings, state renewals, and IRS deadlines with automated reminders and a centralized status view.",
  },
  {
    icon: "\uD83D\uDC65",
    title: "Board Management Tools",
    description:
      "Manage board members, track meeting minutes, record votes, and maintain required governance documentation in one place.",
  },
  {
    icon: "\uD83C\uDFE6",
    title: "Financial Account Integration",
    description:
      "Connect your bank accounts and bookkeeping tools for simplified financial reporting and audit readiness.",
  },
];

const personas = [
  {
    title: "College Students",
    emoji: "\uD83C\uDF93",
    description:
      "Starting a campus organization or social impact project? We help you formalize your group into a real nonprofit so you can accept donations, apply for grants, and make a lasting difference.",
  },
  {
    title: "High Schoolers",
    emoji: "\uD83C\uDFEB",
    description:
      "Turning a community-service idea into something official? TurboCharity walks you through every step, no prior experience needed. Perfect for ambitious students building their future.",
  },
  {
    title: "Grassroots Organizations",
    emoji: "\u270A",
    description:
      "Already making an impact in your community? Going official means tax-exempt donations, credibility with funders, and legal protection for your team.",
  },
];

const pricingTiers = [
  {
    name: "Free",
    price: "$0",
    period: "",
    highlight: false,
    description: "Explore at your own pace",
    features: [
      "Step-by-step nonprofit guides",
      "State requirement checklists",
      "Mission statement builder",
      "Community forum access",
    ],
    cta: "Get Started",
  },
  {
    name: "Starter",
    price: "$49",
    period: "one-time",
    highlight: false,
    description: "Everything to incorporate",
    features: [
      "All Free features",
      "State incorporation filing",
      "AI-generated bylaws",
      "EIN registration assistance",
      "Articles of incorporation",
      "Email support",
    ],
    cta: "Choose Starter",
  },
  {
    name: "Pro",
    price: "$149",
    period: "one-time",
    highlight: true,
    description: "Full 501(c)(3) package",
    features: [
      "All Starter features",
      "IRS Form 1023-EZ auto-fill & filing",
      "Conflict-of-interest policy",
      "Compliance dashboard (1 year)",
      "Board management tools",
      "Priority support",
      "Filing status tracking",
    ],
    cta: "Choose Pro",
  },
];

const testimonials = [
  {
    quote:
      "I went from a napkin idea to a fully registered 501(c)(3) in under two weeks. TurboCharity made the whole process feel effortless.",
    name: "Maria Chen",
    role: "Founder, Bridges for Youth",
    avatar: "MC",
  },
  {
    quote:
      "As a college sophomore, I had no idea where to start. TurboCharity walked me through every step and saved me thousands in legal fees.",
    name: "James Okafor",
    role: "President, Campus Green Initiative",
    avatar: "JO",
  },
  {
    quote:
      "Our grassroots group had been running informally for years. TurboCharity helped us go official and start receiving tax-deductible donations in days.",
    name: "Sarah Kim",
    role: "Director, Neighbors United",
    avatar: "SK",
  },
];

const comparisonRows = [
  {
    feature: "Cost",
    turbo: "$0 \u2013 $149",
    lawyers: "$3,000 \u2013 $5,000+",
    legalzoom: "$599 \u2013 $899+",
    diy: "$0 + filing fees",
  },
  {
    feature: "Time to Complete",
    turbo: "Days",
    lawyers: "3 \u2013 6 months",
    legalzoom: "4 \u2013 8 weeks",
    diy: "Months of research",
  },
  {
    feature: "Compliance Guarantee",
    turbo: "\u2705 Yes",
    lawyers: "\u2705 Yes",
    legalzoom: "\u26A0\uFE0F Limited",
    diy: "\u274C No",
  },
  {
    feature: "State-Specific Support",
    turbo: "\u2705 All 50 states",
    lawyers: "\u26A0\uFE0F Varies",
    legalzoom: "\u26A0\uFE0F Limited",
    diy: "\u274C Manual research",
  },
];

const faqs = [
  {
    question: "How much does it cost to create a nonprofit?",
    answer:
      "With TurboCharity, you can start for free and access basic guides and tools. Our Starter plan ($49) covers state incorporation and AI-generated bylaws. The Pro plan ($149) includes the full 501(c)(3) package with IRS Form 1023-EZ filing. Compare that to $3,000\u2013$5,000+ for a traditional attorney.",
  },
  {
    question: "How long does the process take?",
    answer:
      "Most users complete the TurboCharity questionnaire in under 30 minutes. State filing typically takes 3\u20137 business days depending on your state. IRS 501(c)(3) determination via Form 1023-EZ usually arrives within 2\u20134 weeks. End to end, many users go from idea to tax-exempt status in under a month.",
  },
  {
    question: "Is my organization eligible for 501(c)(3) status?",
    answer:
      "Most charitable, educational, religious, scientific, and literary organizations qualify. During our guided questionnaire we\u2019ll assess your eligibility and let you know immediately if there are any issues. If your organization doesn\u2019t qualify for 501(c)(3), we\u2019ll suggest alternative structures like 501(c)(4) or fiscal sponsorship.",
  },
  {
    question: "What are the state-specific requirements?",
    answer:
      "Every state has different incorporation requirements, filing fees, and ongoing compliance obligations. TurboCharity automatically tailors your documents and filing process to your specific state\u2019s laws. We cover all 50 states plus Washington D.C.",
  },
  {
    question: "Do I need a board of directors?",
    answer:
      "Yes \u2014 most states require a nonprofit to have a board of directors (typically at least 3 members). TurboCharity\u2019s board management tools help you organize your board, track meetings, and maintain required governance records from day one.",
  },
  {
    question: "Can I use TurboCharity if I already have an informal organization?",
    answer:
      "Absolutely! Many of our users are formalizing existing community groups, clubs, or projects. We\u2019ll help you incorporate your existing organization, preserve your brand, and transition smoothly to official nonprofit status with tax-exempt benefits.",
  },
];

/* ------------------------------------------------------------------ */
/*  Page                                                               */
/* ------------------------------------------------------------------ */

export default function Home() {
  return (
    <>
      <Header />

      <main>
        {/* ===== HERO ===== */}
        <section className="relative overflow-hidden bg-gradient-to-b from-blue-50 to-white pb-20 pt-16 sm:pb-28 sm:pt-24">
          {/* decorative blobs */}
          <div className="pointer-events-none absolute -left-40 -top-40 h-[500px] w-[500px] rounded-full bg-blue-100/60 blur-3xl" />
          <div className="pointer-events-none absolute -right-40 top-20 h-[400px] w-[400px] rounded-full bg-primary/5 blur-3xl" />

          <Container className="relative text-center">
            <span className="mb-4 inline-block rounded-full bg-primary/10 px-4 py-1.5 text-xs font-semibold uppercase tracking-wider text-primary">
              TurboTax for Nonprofit Creation
            </span>

            <h1 className="mx-auto max-w-4xl text-4xl font-extrabold leading-tight tracking-tight text-dark sm:text-5xl lg:text-6xl">
              Launch Your Nonprofit{" "}
              <span className="text-primary">in Days, Not Months</span>
            </h1>

            <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-gray-600 sm:text-xl">
              AI-powered 501(c)(3) creation without the expensive lawyers.
              Incorporate, generate bylaws, and file with the IRS &mdash; all
              from one simple platform.
            </p>

            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <Button size="lg" href="#pricing">
                Start Free
              </Button>
              <Button variant="outline" size="lg" href="#how-it-works">
                See How It Works
              </Button>
            </div>

            {/* Stats row */}
            <div className="mx-auto mt-16 grid max-w-3xl grid-cols-1 gap-8 sm:grid-cols-3">
              {stats.map((stat) => (
                <div key={stat.label}>
                  <p className="text-3xl font-extrabold text-primary sm:text-4xl">
                    {stat.value}
                  </p>
                  <p className="mt-1 text-sm font-medium text-gray-500">
                    {stat.label}
                  </p>
                </div>
              ))}
            </div>
          </Container>
        </section>

        {/* ===== HOW IT WORKS ===== */}
        <section id="how-it-works" className="bg-white py-20 sm:py-28">
          <Container>
            <div className="mx-auto max-w-2xl text-center">
              <span className="text-sm font-semibold uppercase tracking-wider text-primary">
                How It Works
              </span>
              <h2 className="mt-3 text-3xl font-extrabold text-dark sm:text-4xl">
                Three Simple Steps to Launch
              </h2>
              <p className="mt-4 text-lg text-gray-500">
                Our guided process turns the complex nonprofit creation journey
                into something anyone can do.
              </p>
            </div>

            <div className="mt-16 grid gap-8 md:grid-cols-3">
              {steps.map((step) => (
                <div
                  key={step.number}
                  className="relative rounded-2xl border border-gray-100 bg-white p-8 shadow-sm transition-shadow hover:shadow-md"
                >
                  {/* number badge */}
                  <span className="mb-5 flex h-12 w-12 items-center justify-center rounded-xl bg-primary text-lg font-bold text-white">
                    {step.number}
                  </span>
                  <span className="mb-3 block text-3xl">{step.icon}</span>
                  <h3 className="text-xl font-bold text-dark">{step.title}</h3>
                  <p className="mt-2 leading-relaxed text-gray-500">
                    {step.description}
                  </p>
                </div>
              ))}
            </div>
          </Container>
        </section>

        {/* ===== FEATURES GRID ===== */}
        <section id="features" className="bg-gray-50 py-20 sm:py-28">
          <Container>
            <div className="mx-auto max-w-2xl text-center">
              <span className="text-sm font-semibold uppercase tracking-wider text-primary">
                Features
              </span>
              <h2 className="mt-3 text-3xl font-extrabold text-dark sm:text-4xl">
                Everything You Need to Go Official
              </h2>
              <p className="mt-4 text-lg text-gray-500">
                From incorporation to IRS filing, we&apos;ve automated the
                hardest parts of starting a nonprofit.
              </p>
            </div>

            <div className="mt-16 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
              {features.map((feature) => (
                <div
                  key={feature.title}
                  className="rounded-2xl border border-gray-100 bg-white p-8 shadow-sm transition-shadow hover:shadow-md"
                >
                  <span className="text-4xl">{feature.icon}</span>
                  <h3 className="mt-4 text-lg font-bold text-dark">
                    {feature.title}
                  </h3>
                  <p className="mt-2 leading-relaxed text-gray-500">
                    {feature.description}
                  </p>
                </div>
              ))}
            </div>
          </Container>
        </section>

        {/* ===== WHO WE SERVE ===== */}
        <section className="bg-white py-20 sm:py-28">
          <Container>
            <div className="mx-auto max-w-2xl text-center">
              <span className="text-sm font-semibold uppercase tracking-wider text-primary">
                Who We Serve
              </span>
              <h2 className="mt-3 text-3xl font-extrabold text-dark sm:text-4xl">
                Built for Changemakers of Every Kind
              </h2>
              <p className="mt-4 text-lg text-gray-500">
                Whether you&apos;re 16 or 60, TurboCharity makes nonprofit
                creation accessible to everyone.
              </p>
            </div>

            <div className="mt-16 grid gap-8 md:grid-cols-3">
              {personas.map((persona) => (
                <div
                  key={persona.title}
                  className="rounded-2xl border border-gray-100 bg-gradient-to-br from-blue-50/50 to-white p-8 shadow-sm transition-shadow hover:shadow-md"
                >
                  <span className="text-5xl">{persona.emoji}</span>
                  <h3 className="mt-4 text-xl font-bold text-dark">
                    {persona.title}
                  </h3>
                  <p className="mt-3 leading-relaxed text-gray-500">
                    {persona.description}
                  </p>
                </div>
              ))}
            </div>
          </Container>
        </section>

        {/* ===== PRICING PREVIEW ===== */}
        <section id="pricing" className="bg-gray-50 py-20 sm:py-28">
          <Container>
            <div className="mx-auto max-w-2xl text-center">
              <span className="text-sm font-semibold uppercase tracking-wider text-primary">
                Pricing
              </span>
              <h2 className="mt-3 text-3xl font-extrabold text-dark sm:text-4xl">
                Simple, Transparent Pricing
              </h2>
              <p className="mt-4 text-lg text-gray-500">
                No hidden fees. No monthly subscriptions. Pay once and launch
                your nonprofit.
              </p>
            </div>

            <div className="mt-16 grid gap-8 md:grid-cols-3">
              {pricingTiers.map((tier) => (
                <div
                  key={tier.name}
                  className={`relative flex flex-col rounded-2xl border p-8 transition-shadow hover:shadow-lg ${
                    tier.highlight
                      ? "border-primary bg-white shadow-xl ring-2 ring-primary"
                      : "border-gray-200 bg-white shadow-sm"
                  }`}
                >
                  {tier.highlight && (
                    <span className="absolute -top-3.5 left-1/2 -translate-x-1/2 rounded-full bg-primary px-4 py-1 text-xs font-bold uppercase tracking-wider text-white">
                      Most Popular
                    </span>
                  )}

                  <h3 className="text-lg font-bold text-dark">{tier.name}</h3>
                  <p className="mt-1 text-sm text-gray-500">
                    {tier.description}
                  </p>

                  <div className="mt-6">
                    <span className="text-4xl font-extrabold text-dark">
                      {tier.price}
                    </span>
                    {tier.period && (
                      <span className="ml-1 text-sm text-gray-400">
                        /{tier.period}
                      </span>
                    )}
                  </div>

                  <ul className="mt-8 flex-1 space-y-3">
                    {tier.features.map((feat) => (
                      <li
                        key={feat}
                        className="flex items-start gap-2 text-sm text-gray-600"
                      >
                        <svg
                          className="mt-0.5 h-4 w-4 shrink-0 text-secondary"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          strokeWidth={3}
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            d="M5 13l4 4L19 7"
                          />
                        </svg>
                        {feat}
                      </li>
                    ))}
                  </ul>

                  <div className="mt-8">
                    <Button
                      variant={tier.highlight ? "primary" : "outline"}
                      className="w-full"
                    >
                      {tier.cta}
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          </Container>
        </section>

        {/* ===== TESTIMONIALS ===== */}
        <section className="bg-white py-20 sm:py-28">
          <Container>
            <div className="mx-auto max-w-2xl text-center">
              <span className="text-sm font-semibold uppercase tracking-wider text-primary">
                Testimonials
              </span>
              <h2 className="mt-3 text-3xl font-extrabold text-dark sm:text-4xl">
                Loved by Founders Nationwide
              </h2>
            </div>

            <div className="mt-16 grid gap-8 md:grid-cols-3">
              {testimonials.map((t) => (
                <div
                  key={t.name}
                  className="flex flex-col rounded-2xl border border-gray-100 bg-white p-8 shadow-sm"
                >
                  <blockquote className="flex-1 text-gray-600 leading-relaxed">
                    &ldquo;{t.quote}&rdquo;
                  </blockquote>

                  <div className="mt-6 flex items-center gap-4 border-t border-gray-100 pt-6">
                    {/* Avatar placeholder */}
                    <span className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-sm font-bold text-primary">
                      {t.avatar}
                    </span>
                    <div>
                      <p className="text-sm font-semibold text-dark">
                        {t.name}
                      </p>
                      <p className="text-xs text-gray-400">{t.role}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </Container>
        </section>

        {/* ===== COMPARISON SECTION ===== */}
        <section className="bg-gray-50 py-20 sm:py-28">
          <Container>
            <div className="mx-auto max-w-2xl text-center">
              <span className="text-sm font-semibold uppercase tracking-wider text-primary">
                Compare
              </span>
              <h2 className="mt-3 text-3xl font-extrabold text-dark sm:text-4xl">
                See How We Stack Up
              </h2>
              <p className="mt-4 text-lg text-gray-500">
                TurboCharity delivers attorney-quality results at a fraction of
                the cost and time.
              </p>
            </div>

            <div className="mt-12 overflow-x-auto">
              <table className="mx-auto w-full max-w-4xl text-left text-sm">
                <thead>
                  <tr className="border-b border-gray-200">
                    <th className="py-4 pr-6 font-semibold text-gray-500"></th>
                    <th className="px-4 py-4 font-bold text-primary">
                      TurboCharity
                    </th>
                    <th className="px-4 py-4 font-semibold text-gray-700">
                      Lawyers
                    </th>
                    <th className="px-4 py-4 font-semibold text-gray-700">
                      LegalZoom
                    </th>
                    <th className="px-4 py-4 font-semibold text-gray-700">
                      DIY
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {comparisonRows.map((row) => (
                    <tr
                      key={row.feature}
                      className="border-b border-gray-100 last:border-none"
                    >
                      <td className="py-4 pr-6 font-medium text-dark">
                        {row.feature}
                      </td>
                      <td className="px-4 py-4 font-semibold text-primary">
                        {row.turbo}
                      </td>
                      <td className="px-4 py-4 text-gray-600">
                        {row.lawyers}
                      </td>
                      <td className="px-4 py-4 text-gray-600">
                        {row.legalzoom}
                      </td>
                      <td className="px-4 py-4 text-gray-600">{row.diy}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Container>
        </section>

        {/* ===== FAQ SECTION ===== */}
        <section id="faq" className="bg-white py-20 sm:py-28">
          <Container>
            <div className="mx-auto max-w-2xl text-center">
              <span className="text-sm font-semibold uppercase tracking-wider text-primary">
                FAQ
              </span>
              <h2 className="mt-3 text-3xl font-extrabold text-dark sm:text-4xl">
                Frequently Asked Questions
              </h2>
              <p className="mt-4 text-lg text-gray-500">
                Everything you need to know about starting your nonprofit.
              </p>
            </div>

            <div className="mx-auto mt-12 max-w-3xl divide-y divide-gray-200">
              {faqs.map((faq) => (
                <details
                  key={faq.question}
                  className="group py-5 [&_summary::-webkit-details-marker]:hidden"
                >
                  <summary className="flex cursor-pointer items-center justify-between font-semibold text-dark transition-colors hover:text-primary">
                    <span>{faq.question}</span>
                    <span className="ml-4 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-gray-300 text-gray-400 transition-transform group-open:rotate-45 group-open:border-primary group-open:text-primary">
                      +
                    </span>
                  </summary>
                  <p className="mt-3 leading-relaxed text-gray-500">
                    {faq.answer}
                  </p>
                </details>
              ))}
            </div>
          </Container>
        </section>

        {/* ===== FINAL CTA ===== */}
        <section className="bg-gradient-to-br from-primary to-blue-700 py-20 sm:py-28">
          <Container className="text-center">
            <h2 className="text-3xl font-extrabold text-white sm:text-4xl lg:text-5xl">
              Ready to Make a Difference?
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-lg leading-relaxed text-blue-100">
              Join thousands of changemakers who launched their nonprofits with
              TurboCharity. Start for free &mdash; no credit card required.
            </p>

            <div className="mx-auto mt-10 flex justify-center">
              <NewsletterSignup dark />
            </div>
          </Container>
        </section>
      </main>

      <Footer />
    </>
  );
}
