'use client';

import { useState } from 'react';
import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Container from '@/components/Container';

/* ── Static data ────────────────────────────────────────────── */

const CATEGORIES = [
  'Education',
  'Health & Wellness',
  'Environment',
  'Animal Welfare',
  'Arts & Culture',
  'Community Development',
  'Human Services',
  'International Aid',
  'Religion & Spirituality',
  'Science & Research',
  'Youth Development',
  'Other',
] as const;

const US_STATES = [
  'Alabama','Alaska','Arizona','Arkansas','California','Colorado',
  'Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho',
  'Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana',
  'Maine','Maryland','Massachusetts','Michigan','Minnesota',
  'Mississippi','Missouri','Montana','Nebraska','Nevada',
  'New Hampshire','New Jersey','New Mexico','New York',
  'North Carolina','North Dakota','Ohio','Oklahoma','Oregon',
  'Pennsylvania','Rhode Island','South Carolina','South Dakota',
  'Tennessee','Texas','Utah','Vermont','Virginia','Washington',
  'West Virginia','Wisconsin','Wyoming','District of Columbia',
] as const;

const ROLES = ['Founder', 'Board Member', 'Volunteer'] as const;

const PRICING_TIERS = [
  {
    id: 'starter',
    name: 'Starter',
    price: 0,
    tagline: 'For those just exploring',
    features: [
      'State incorporation filing',
      'Basic bylaws template',
      'EIN application guidance',
      'Email support',
    ],
  },
  {
    id: 'standard',
    name: 'Standard',
    price: 149,
    tagline: 'Most popular for new nonprofits',
    features: [
      'Everything in Starter',
      'AI-generated bylaws',
      'IRS Form 1023-EZ auto-fill',
      'Conflict of interest policy',
      'Priority email support',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 349,
    tagline: 'Full-service launch package',
    features: [
      'Everything in Standard',
      '1-on-1 consultation call',
      'Board governance toolkit',
      'Fundraising starter pack',
      'Dedicated account manager',
      '90-day post-filing support',
    ],
  },
] as const;

/* ── Types ──────────────────────────────────────────────────── */

interface FormState {
  mission: string;
  category: string;
  state: string;
  name: string;
  email: string;
  phone: string;
  role: string;
  selectedTier: string;
}

const TOTAL_STEPS = 4;

/* ── Helpers ────────────────────────────────────────────────── */

function recommendTier(form: FormState): string {
  if (form.role === 'Volunteer' || form.mission.length < 50) return 'starter';
  if (form.role === 'Board Member') return 'standard';
  return 'standard';
}

/* ── Progress Bar ───────────────────────────────────────────── */

function ProgressBar({ step }: { step: number }) {
  const pct = (step / TOTAL_STEPS) * 100;
  return (
    <div className="mb-8">
      <div className="mb-2 flex items-center justify-between text-xs font-medium text-gray-500">
        <span>Step {step} of {TOTAL_STEPS}</span>
        <span>{Math.round(pct)}% complete</span>
      </div>
      <div className="h-2 w-full overflow-hidden rounded-full bg-gray-200">
        <div
          className="h-full rounded-full bg-primary transition-all duration-500"
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  );
}

/* ── Page ───────────────────────────────────────────────────── */

export default function GetStartedPage() {
  const [step, setStep] = useState(1);
  const [form, setForm] = useState<FormState>({
    mission: '',
    category: '',
    state: '',
    name: '',
    email: '',
    phone: '',
    role: '',
    selectedTier: '',
  });
  const [submitted, setSubmitted] = useState(false);

  function update(fields: Partial<FormState>) {
    setForm((prev) => ({ ...prev, ...fields }));
  }

  function next() {
    setStep((s) => Math.min(s + 1, TOTAL_STEPS));
  }

  function back() {
    setStep((s) => Math.max(s - 1, 1));
  }

  function handleSubmit() {
    console.log('--- TurboCharity Signup Submission ---');
    console.log(JSON.stringify(form, null, 2));
    setSubmitted(true);
  }

  /* ─ Validation per step ─ */
  const canAdvance: Record<number, boolean> = {
    1: form.mission.trim().length > 0 && form.category.length > 0,
    2: form.state.length > 0,
    3: form.name.trim().length > 0 && form.email.trim().length > 0 && form.role.length > 0,
    4: form.selectedTier.length > 0,
  };

  if (submitted) {
    return (
      <>
        <Header />
        <main className="flex min-h-[70vh] items-center justify-center bg-gray-50">
          <div className="mx-auto max-w-lg rounded-2xl bg-white p-10 text-center shadow-lg">
            <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-secondary/10 text-secondary">
              <svg className="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <h1 className="text-2xl font-bold text-dark">You&apos;re all set!</h1>
            <p className="mt-2 text-gray-600">
              We&apos;ve received your information. Check your email for next steps.
            </p>
            <Link
              href="/thank-you"
              className="mt-6 inline-block rounded-lg bg-primary px-6 py-3 text-sm font-semibold text-white hover:bg-blue-700"
            >
              Continue to Next Steps
            </Link>
          </div>
        </main>
        <Footer />
      </>
    );
  }

  return (
    <>
      <Header />
      <main className="min-h-screen bg-gray-50 py-12">
        <Container className="max-w-2xl">
          <ProgressBar step={step} />

          <div className="rounded-2xl bg-white p-8 shadow-lg sm:p-10">
            {/* ── Step 1 ───────────────────────────── */}
            {step === 1 && (
              <div>
                <h2 className="text-2xl font-bold text-dark">
                  What&apos;s your nonprofit&apos;s mission?
                </h2>
                <p className="mt-1 text-sm text-gray-500">
                  Tell us about the change you want to create in the world.
                </p>

                <label className="mt-6 block">
                  <span className="text-sm font-medium text-gray-700">Mission statement</span>
                  <textarea
                    rows={4}
                    value={form.mission}
                    onChange={(e) => update({ mission: e.target.value })}
                    placeholder="e.g. Provide free tutoring to underserved students in rural communities..."
                    className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-3 text-sm shadow-sm placeholder:text-gray-400 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
                  />
                </label>

                <label className="mt-5 block">
                  <span className="text-sm font-medium text-gray-700">Category</span>
                  <select
                    value={form.category}
                    onChange={(e) => update({ category: e.target.value })}
                    className="mt-1 block w-full rounded-lg border border-gray-300 bg-white px-4 py-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
                  >
                    <option value="">Select a category</option>
                    {CATEGORIES.map((cat) => (
                      <option key={cat} value={cat}>{cat}</option>
                    ))}
                  </select>
                </label>
              </div>
            )}

            {/* ── Step 2 ───────────────────────────── */}
            {step === 2 && (
              <div>
                <h2 className="text-2xl font-bold text-dark">
                  Where will you incorporate?
                </h2>
                <p className="mt-1 text-sm text-gray-500">
                  Choose the state where your nonprofit will be legally established.
                </p>

                <label className="mt-6 block">
                  <span className="text-sm font-medium text-gray-700">State</span>
                  <select
                    value={form.state}
                    onChange={(e) => update({ state: e.target.value })}
                    className="mt-1 block w-full rounded-lg border border-gray-300 bg-white px-4 py-3 text-sm shadow-sm focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
                  >
                    <option value="">Select a state</option>
                    {US_STATES.map((st) => (
                      <option key={st} value={st}>{st}</option>
                    ))}
                  </select>
                </label>

                <div className="mt-6 rounded-lg border border-blue-100 bg-blue-50 p-4">
                  <h3 className="text-sm font-semibold text-blue-800">Did you know?</h3>
                  <p className="mt-1 text-xs text-blue-700">
                    Delaware, California, and Texas are among the most popular states for nonprofit
                    incorporation due to favorable regulations and low filing fees.
                  </p>
                </div>
              </div>
            )}

            {/* ── Step 3 ───────────────────────────── */}
            {step === 3 && (
              <div>
                <h2 className="text-2xl font-bold text-dark">About you</h2>
                <p className="mt-1 text-sm text-gray-500">
                  Tell us a bit about yourself so we can personalize your experience.
                </p>

                <div className="mt-6 space-y-5">
                  <label className="block">
                    <span className="text-sm font-medium text-gray-700">Full name *</span>
                    <input
                      type="text"
                      value={form.name}
                      onChange={(e) => update({ name: e.target.value })}
                      placeholder="Jane Smith"
                      className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-3 text-sm shadow-sm placeholder:text-gray-400 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
                    />
                  </label>

                  <label className="block">
                    <span className="text-sm font-medium text-gray-700">Email *</span>
                    <input
                      type="email"
                      value={form.email}
                      onChange={(e) => update({ email: e.target.value })}
                      placeholder="jane@example.com"
                      className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-3 text-sm shadow-sm placeholder:text-gray-400 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
                    />
                  </label>

                  <label className="block">
                    <span className="text-sm font-medium text-gray-700">
                      Phone <span className="text-gray-400">(optional)</span>
                    </span>
                    <input
                      type="tel"
                      value={form.phone}
                      onChange={(e) => update({ phone: e.target.value })}
                      placeholder="(555) 123-4567"
                      className="mt-1 block w-full rounded-lg border border-gray-300 px-4 py-3 text-sm shadow-sm placeholder:text-gray-400 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
                    />
                  </label>

                  <fieldset>
                    <legend className="text-sm font-medium text-gray-700">Your role *</legend>
                    <div className="mt-2 flex flex-wrap gap-3">
                      {ROLES.map((r) => (
                        <button
                          key={r}
                          type="button"
                          onClick={() => update({ role: r })}
                          className={`rounded-full border px-5 py-2 text-sm font-medium transition-colors ${
                            form.role === r
                              ? 'border-primary bg-primary/10 text-primary'
                              : 'border-gray-300 text-gray-600 hover:border-primary/40'
                          }`}
                        >
                          {r}
                        </button>
                      ))}
                    </div>
                  </fieldset>
                </div>
              </div>
            )}

            {/* ── Step 4 ───────────────────────────── */}
            {step === 4 && (
              <div>
                <h2 className="text-2xl font-bold text-dark">Your plan</h2>
                <p className="mt-1 text-sm text-gray-500">
                  Based on your inputs we recommend the{' '}
                  <span className="font-semibold text-primary">
                    {PRICING_TIERS.find((t) => t.id === recommendTier(form))?.name}
                  </span>{' '}
                  plan. Pick any tier that suits you.
                </p>

                <div className="mt-6 grid gap-4 sm:grid-cols-3">
                  {PRICING_TIERS.map((tier) => {
                    const isRecommended = tier.id === recommendTier(form);
                    const isSelected = form.selectedTier === tier.id;
                    return (
                      <button
                        key={tier.id}
                        type="button"
                        onClick={() => update({ selectedTier: tier.id })}
                        className={`relative flex flex-col rounded-xl border-2 p-5 text-left transition-all ${
                          isSelected
                            ? 'border-primary bg-primary/5 shadow-md'
                            : 'border-gray-200 hover:border-primary/40'
                        }`}
                      >
                        {isRecommended && (
                          <span className="absolute -top-3 left-4 rounded-full bg-secondary px-3 py-0.5 text-[10px] font-bold uppercase tracking-wider text-white">
                            Recommended
                          </span>
                        )}
                        <span className="text-lg font-bold text-dark">{tier.name}</span>
                        <span className="mt-1 text-2xl font-extrabold text-primary">
                          {tier.price === 0 ? 'Free' : `$${tier.price}`}
                        </span>
                        <span className="mt-1 text-xs text-gray-500">{tier.tagline}</span>
                        <ul className="mt-4 space-y-2">
                          {tier.features.map((f) => (
                            <li key={f} className="flex items-start gap-2 text-xs text-gray-600">
                              <svg className="mt-0.5 h-3.5 w-3.5 shrink-0 text-secondary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                              </svg>
                              {f}
                            </li>
                          ))}
                        </ul>
                      </button>
                    );
                  })}
                </div>

                {/* Summary */}
                {form.selectedTier && (
                  <div className="mt-8 rounded-lg border border-gray-200 bg-gray-50 p-5">
                    <h3 className="text-sm font-semibold text-dark">Summary</h3>
                    <dl className="mt-3 space-y-2 text-sm text-gray-600">
                      <div className="flex justify-between">
                        <dt>Mission</dt>
                        <dd className="max-w-[60%] truncate text-right font-medium text-dark">
                          {form.mission}
                        </dd>
                      </div>
                      <div className="flex justify-between">
                        <dt>Category</dt>
                        <dd className="font-medium text-dark">{form.category}</dd>
                      </div>
                      <div className="flex justify-between">
                        <dt>State</dt>
                        <dd className="font-medium text-dark">{form.state}</dd>
                      </div>
                      <div className="flex justify-between">
                        <dt>Name</dt>
                        <dd className="font-medium text-dark">{form.name}</dd>
                      </div>
                      <div className="flex justify-between">
                        <dt>Email</dt>
                        <dd className="font-medium text-dark">{form.email}</dd>
                      </div>
                      {form.phone && (
                        <div className="flex justify-between">
                          <dt>Phone</dt>
                          <dd className="font-medium text-dark">{form.phone}</dd>
                        </div>
                      )}
                      <div className="flex justify-between">
                        <dt>Role</dt>
                        <dd className="font-medium text-dark">{form.role}</dd>
                      </div>
                      <div className="flex justify-between border-t border-gray-200 pt-2">
                        <dt className="font-semibold text-dark">Plan</dt>
                        <dd className="font-bold text-primary">
                          {PRICING_TIERS.find((t) => t.id === form.selectedTier)?.name} &mdash;{' '}
                          {PRICING_TIERS.find((t) => t.id === form.selectedTier)?.price === 0
                            ? 'Free'
                            : `$${PRICING_TIERS.find((t) => t.id === form.selectedTier)?.price}`}
                        </dd>
                      </div>
                    </dl>
                  </div>
                )}
              </div>
            )}

            {/* ── Navigation ─────────────────────── */}
            <div className="mt-8 flex items-center justify-between">
              {step > 1 ? (
                <button
                  type="button"
                  onClick={back}
                  className="rounded-lg border border-gray-300 px-5 py-2.5 text-sm font-medium text-gray-600 transition-colors hover:bg-gray-50"
                >
                  Back
                </button>
              ) : (
                <span />
              )}

              {step < TOTAL_STEPS ? (
                <button
                  type="button"
                  onClick={next}
                  disabled={!canAdvance[step]}
                  className="rounded-lg bg-primary px-6 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-40"
                >
                  Continue
                </button>
              ) : (
                <button
                  type="button"
                  onClick={handleSubmit}
                  disabled={!canAdvance[step]}
                  className="rounded-lg bg-secondary px-6 py-2.5 text-sm font-semibold text-white transition-colors hover:bg-emerald-600 disabled:cursor-not-allowed disabled:opacity-40"
                >
                  Submit
                </button>
              )}
            </div>
          </div>
        </Container>
      </main>
      <Footer />
    </>
  );
}
